version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    expose:
      - "3001"
    volumes:
      - ./backend/backend.sock:/backend.sock  # Монтируем UNIX-сокет бэкенда в контейнер
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    expose:
      - "3000"
    volumes:
      - ./frontend/frontend.sock:/frontend.sock  # Монтируем UNIX-сокет фронтенда в контейнер
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
